force-app/main/default/objects/Trigger_Event__e/Trigger_Event__e.object-meta.xml
<CustomObject>
    <label>Trigger Event</label>
    <pluralLabel>Trigger Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Event__e/fields/Error_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Error_Reasons__c</fullName>
    <label>Error Reasons</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Event__e/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Event__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Log__c/Trigger_Log__c.object-meta.xml
<CustomObject>
    <label>Trigger Log</label>
    <nameField>
        <label>Trigger_Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Log__c/fields/Error_Reason__c.field-meta.xml
<CustomField>
    <fullName>Error_Reason__c</fullName>
    <label>Error Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Log__c/fields/Error_Reason_Short__c.field-meta.xml
<CustomField>
    <fullName>Error_Reason_Short__c</fullName>
    <label>Error Reason Short</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Log__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INSERT</fullName>
            </value>
            <value>
                <fullName>UPDATE</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>UNDELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerLogGenerator.cls
public class TriggerLogGenerator {
    private static final List<String> objectList = new List<String>{
        'Account', 'Contact', 'Opportunity', 'Case', 'Lead', 'Campaign', 'User', 'Task'};

    public static void logTriggerSummary(String objectName, String operation, String eMessage) {
        List<Trigger_Log__c> logsToInsert = new List<Trigger_Log__c>();
 		
        Trigger_Log__c log = new Trigger_Log__c();
        log.Name = 'Log - ' + objectName + ' Trigger';
        log.Object__c = objectName;
        log.Operation__c = operation.substring(operation.indexOf('_') + 1);
        
        if(eMessage == null){
            log.Result__c = 'Success';
        }
        else{
            log.Result__c = 'Error';
            log.Error_Reason__c = eMessage;
            Integer endIdx = Math.min(255, eMessage.length());
            log.Error_Reason_Short__c = eMessage.substring(0, endIdx);
        }
        logsToInsert.add(log);
        
        if (!logsToInsert.isEmpty()) {
            insert logsToInsert;
        }
    }
    
    public static void hanldeTriggerException(String objectName, String operation, String err){
        Trigger_Event__e evt = new Trigger_Event__e(
            Object_Name__c = objectName, Operation__c = operation, Error_Reasons__c = err
        );    
        Database.SaveResult result = EventBus.publish(evt);
        System.debug('Publish Status: ' + result.isSuccess());
    }
}